# -*- mode: ruby -*-
# vi: set ft=ruby :

# Derive box id of format <box>_<version>_<provider> from path of this Vagrantfile
# which looks like: /home/<user>/.vagrant.d/boxes/<box>/<version>/<provider>/Vagrantfile
box_id = __FILE__.split(File::SEPARATOR)[-4, 3].join('_')

# Copy cloud-init image to ensure QEMU/KVM can read it
cloud_init_dest = "/var/tmp/#{box_id}_vagrant_cloud_init.iso"
if not File.exist?(cloud_init_dest)
  FileUtils.cp(File.expand_path('../cloud-init.iso', __FILE__), cloud_init_dest)
end

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.connect_via_ssh = false
    libvirt.username = "root"
    libvirt.storage_pool_name = "default"
    libvirt.storage :file, :device => :cdrom, :path => cloud_init_dest
  end
end
